### ISSUE TITLE
Use std.http.headers

### ISSUE THREAD

**Issue by daurnimator** [truemedian/hzzp#1]
(comment from it):

> Design criteria:
>   - the same header field is allowed more than once
>   - must be able to fetch separate occurrences (important for some headers e.g. Set-Cookie)
>   - optionally available as comma separated list
>   - http2 adds flag to headers that they should never be indexed
>   - header order should be recoverable
> 
> Headers are implemented as an array of entries.
> An index of field name => array indices is kept.

**Comment by truemedian** [comment]
I'll definitely look into this. At the moment I was simply shipping a simpler Headers struct. However another thing to note is that hzzp.low cannot use std.http.HeaderEntry because of the allocation it requires. I might end up having std.http.Headers for hzzp.allocating, but hzzp.low will always need its own, non-allocating Header.

**Comment by truemedian** [comment]
hzzp.basic.Request is now using std.http.Headers to store headers. std.http.Headers doesn't fit hzzp.base.Client and hzzp.base.Server, where headers are emitted one by one.

**Comment by daurnimator** [comment]
Note that method/path/status are considered headers:
e.g.
  - the `:method` header should contain the method
  - the `:path` header should contain the path (with query params)
  - the `:authority` header should be used instead of `host`
  - for responses, `:status` should contain the status code.

**Comment by truemedian** [comment]
I don't plan on implementing those because:
- RFC7231 (HTTP/1.1) does not define them as headers. (I'm aware that HTTP/2.0 does).
- Parsing the status line is already semi-complicated, I don't want it to be more complicated.
